### ISSUE TITLE
Доработки интерфейса

### ISSUE THREAD

**Issue by f0reXwQw** [Blasx/034MusicLibrary#5]
- [x] Сделать редактирование треков
- [x] Сделать сериализацию одного трека
- [x] Добавить поле "название треклиста" в модель треклиста
- [x] Добавить в интерфейс название треклистов
- [x] Обозначить текстовое поле

**Comment by SergeyKostin** [comment]
https://github.com/SergeyKostin/Project_1/commit/21ffa4a06a3abd39808e8616ae179ac6c2e40295
